"use client"
import Head from "next/head"
import Login from "./compontens/Login"
import {useAuthState} from 'react-firebase-hooks/auth'
import { Auth } from "../../config/firebase"
import Row from './compontens/Row'

import  MovieDetails  from './compontens/MovieDetails';
import requests from "@/utils/requests"



export default function Home()  {
 
const [user] = useAuthState(Auth)

if (!user) return <Login/>

  return (
<>
<Head>
  <title>Netflix</title>
  <meta name='description' content="Generated by create next app"/>
  <meta name='viewport' content="width=device, initial-scale-1"/>
  

</Head>

<main   className="relative bg-gradient-to-b from-gray-900/10 to-[#010511]">
< MovieDetails  /> 
</main>
<div  className=" bg-gradient-to-r from-black" >
<Row rowID='1' title='Up Coming'fetchURL={requests.requestUpcoming} />
<Row rowID='2' title='Popular'fetchURL={requests.requestPopular} />
<Row rowID='3' title='Trending'fetchURL={requests.requestTrending} />
<Row rowID='4' title='Top Rated'fetchURL={requests.requestTopRated} />
<Row rowID='5' title='Horror'fetchURL={requests.requestHorror} />
</div>



</>
  )
}





